# NeuralProphet for Multivariate Time Series

We quickly test how effective Neural Prophet is at forecasting multivariate time series.

## Packages

In [23]:
import requests 
import os
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
from sklearn.linear_model import LinearRegression

from prophet import Prophet
from pandas.tseries.holiday import USFederalHolidayCalendar
from prophet.diagnostics import cross_validation, performance_metrics
from prophet.plot import plot_cross_validation_metric
from prophet.plot import add_changepoints_to_plot
from prophet.plot import plot_plotly, plot_components_plotly
import itertools

import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning
warnings.simplefilter('ignore', ConvergenceWarning)

import optuna
from neuralprophet import NeuralProphet
import logging

## Data Preparation

In [24]:
rs = pd.read_csv('../../scr/data/cleaned_rat_sightings_data/all_daily_borough_rs.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 

rs = rs[rs['created_date']<'2026-03-01']
rs = rs[rs['created_date']>='2020-01-01']

rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

BOROUGHS = ['BRONX', 'BROOKLYN', 'MANHATTAN', 'QUEENS', 'STATEN ISLAND']

df = rs.copy()

## Model

In [79]:
import pandas as pd
import matplotlib.pyplot as plt
from neuralprophet import NeuralProphet

# Boroughs
BOROUGHS = ['BRONX', 'BROOKLYN', 'MANHATTAN', 'QUEENS', 'STATEN ISLAND']

# Ensure datetime
df['ds'] = pd.to_datetime(df['ds'])

# Create full date range
full_dates = pd.date_range('2020-01-01', '2026-02-28', freq='D')
full_index = pd.MultiIndex.from_product([full_dates, BOROUGHS], names=['ds','borough'])

# Reindex and fill missing
df_full = df.set_index(['ds','borough']).reindex(full_index).reset_index()
df_full['y'] = df_full['y'].fillna(0)
df_full = df_full.rename(columns={'borough':'ID'})

# Train NeuralProphet
m = NeuralProphet(
    yearly_seasonality=True,
    weekly_seasonality=True
)
m.fit(df_full, freq='D')

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 99.956% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 99.956% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 99.956% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 99.956% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 99.956% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.utils.set_auto_seasonalities) - Disabling daily seasonality. Run NeuralProphet with daily_seasonality=True to override this.
INFO - (NP.config.set_auto_batch_epoch) - Auto-set batch_size to 128
INFO - (NP.config.set_auto_batch_epoch) - Auto-set epochs to 50
WARNING - (py.warnings._showwarnmsg) - /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages/pytorch_lightning/trainer/setup.py:201: UserWarning:

MPS available but not used. Set `accelerator` and `devices` using `Trainer(accelerator='mps', devices=1)`.


WARNING - (NP.config.set_lr_finder_args) - Learning rate finder: The number of batches (88) is too small than the required number                     for the learning rate finder (251). The results might not be optimal.

Finding best initial lr:   0%|          | 0/251 [00:00<?, ?it/s]

WARNING - (py.warnings._showwarnmsg) - /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages/lightning_fabric/utilities/cloud_io.py:51: FutureWarning:

You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.

Training: 0it [00:00, ?it/s]

         MAE      RMSE      Loss  RegLoss  epoch
0   0.658977  0.809130  0.391009      0.0      0
1   0.306135  0.388491  0.140338      0.0      1
2   0.183102  0.241861  0.062440      0.0      2
3   0.179495  0.237630  0.060309      0.0      3
4   0.178440  0.237078  0.059890      0.0      4
5   0.179375  0.238401  0.060445      0.0      5
6   0.179313  0.239224  0.060570      0.0      6
7   0.181161  0.240636  0.061570      0.0      7
8   0.179626  0.238748  0.060667      0.0      8
9   0.181301  0.240076  0.061341      0.0      9
10  0.181796  0.241440  0.062041      0.0     10
11  0.183250  0.242992  0.062580      0.0     11
12  0.182462  0.241806  0.062152      0.0     12
13  0.182368  0.242094  0.062230      0.0     13
14  0.184584  0.244147  0.063462      0.0     14
15  0.183870  0.243449  0.062879      0.0     15
16  0.183148  0.242476  0.062409      0.0     16
17  0.182137  0.242279  0.062262      0.0     17
18  0.182636  0.242093  0.062510      0.0     18
19  0.182028  0.241531  0.061909      0.0     19
20  0.181989  0.241221  0.061843      0.0     20
21  0.180713  0.240045  0.061307      0.0     21
22  0.179923  0.239167  0.060918      0.0     22
23  0.179642  0.239150  0.060607      0.0     23
24  0.178703  0.238042  0.060126      0.0     24
25  0.177861  0.236857  0.059736      0.0     25
26  0.178793  0.237815  0.060123      0.0     26
27  0.177285  0.236478  0.059379      0.0     27
28  0.177000  0.235519  0.059236      0.0     28
29  0.176705  0.235371  0.059100      0.0     29
30  0.176760  0.235773  0.059131      0.0     30
31  0.176911  0.236001  0.059176      0.0     31
32  0.176769  0.235761  0.059124      0.0     32
33  0.176987  0.235957  0.059202      0.0     33
34  0.176516  0.235345  0.058996      0.0     34
35  0.176366  0.235057  0.058901      0.0     35
36  0.176653  0.235816  0.059062      0.0     36
37  0.176525  0.235484  0.059003      0.0     37
38  0.176595  0.235288  0.059011      0.0     38
39  0.176257  0.235399  0.058900      0.0     39
40  0.176421  0.235132  0.058941      0.0     40
41  0.176455  0.235040  0.058899      0.0     41
42  0.176254  0.235350  0.058833      0.0     42
43  0.176206  0.234864  0.058801      0.0     43
44  0.176237  0.235070  0.058828      0.0     44
45  0.176092  0.235118  0.058755      0.0     45
46  0.176094  0.235018  0.058746      0.0     46
47  0.176043  0.234737  0.058737      0.0     47
48  0.175985  0.234438  0.058705      0.0     48
49  0.176053  0.234896  0.058730      0.0     49

In [84]:
# Forecast horizon
forecast_horizon = 14

# Dictionary to store 14-day forecasts per borough
forecast_by_borough = {}

for b in BOROUGHS:
    # Filter data for this borough
    df_b = df_full[df_full['ID'] == b].copy()
    
    # Make future dataframe for 14 days
    future_b = m.make_future_dataframe(df_b, periods=forecast_horizon, n_historic_predictions=0)
    
    # Predict using the existing model
    forecast_b = m.predict(future_b)
    
    # Extract only the 14-day forecast (future beyond training)
    forecast_14d_b = forecast_b[forecast_b['ds'] > df_b['ds'].max()][['ds', 'yhat1']].reset_index(drop=True)
    
    # Store in dictionary
    forecast_by_borough[b] = forecast_14d_b

INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 99.956% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 92.857% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 92.857% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D

Predicting: 88it [00:00, ?it/s]

INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 99.956% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 92.857% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 92.857% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D

Predicting: 88it [00:00, ?it/s]

INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 99.956% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 92.857% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 92.857% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D

Predicting: 88it [00:00, ?it/s]

INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 99.956% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 92.857% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 92.857% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D

Predicting: 88it [00:00, ?it/s]

INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 99.956% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 92.857% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 92.857% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D

Predicting: 88it [00:00, ?it/s]

In [85]:
forecast_by_borough

{'BRONX':            ds     yhat1
 0  2026-03-01  2.573042
 1  2026-03-02  6.515988
 2  2026-03-03  6.409023
 3  2026-03-04  6.217506
 4  2026-03-05  5.967527
 5  2026-03-06  5.099592
 6  2026-03-07  2.611990
 7  2026-03-08  2.821991
 8  2026-03-09  6.757502
 9  2026-03-10  6.642254
 10 2026-03-11  6.441811
 11 2026-03-12  6.182206
 12 2026-03-13  5.302453
 13 2026-03-14  2.800583,
 'BROOKLYN':            ds      yhat1
 0  2026-03-01   6.094047
 1  2026-03-02  15.432605
 2  2026-03-03  15.179264
 3  2026-03-04  14.725672
 4  2026-03-05  14.133616
 5  2026-03-06  12.077982
 6  2026-03-07   6.186292
 7  2026-03-08   6.683662
 8  2026-03-09  16.004610
 9  2026-03-10  15.731655
 10 2026-03-11  15.256920
 11 2026-03-12  14.642066
 12 2026-03-13  12.558442
 13 2026-03-14   6.632959,
 'MANHATTAN':            ds      yhat1
 0  2026-03-01   4.198121
 1  2026-03-02  10.631350
 2  2026-03-03  10.456827
 3  2026-03-04  10.144352
 4  2026-03-05   9.736491
 5  2026-03-06   8.320388
 6  2026-03-07   4.261668
 7  2026-03-08   4.604301
 8  2026-03-09  11.025398
 9  2026-03-10  10.837362
 10 2026-03-11  10.510323
 11 2026-03-12  10.086757
 12 2026-03-13   8.651371
 13 2026-03-14   4.569372,
 'QUEENS':            ds     yhat1
 0  2026-03-01  2.843889
 1  2026-03-02  7.201882
 2  2026-03-03  7.083657
 3  2026-03-04  6.871980
 4  2026-03-05  6.595687
 5  2026-03-06  5.636392
 6  2026-03-07  2.886936
 7  2026-03-08  3.119042
 8  2026-03-09  7.468818
 9  2026-03-10  7.341439
 10 2026-03-11  7.119896
 11 2026-03-12  6.832964
 12 2026-03-13  5.860606
 13 2026-03-14  3.095381,
 'STATEN ISLAND':            ds     yhat1
 0  2026-03-01  0.677116
 1  2026-03-02  1.714734
 2  2026-03-03  1.686585
 3  2026-03-04  1.636186
 4  2026-03-05  1.570402
 5  2026-03-06  1.341998
 6  2026-03-07  0.687366
 7  2026-03-08  0.742629
 8  2026-03-09  1.778290
 9  2026-03-10  1.747962
 10 2026-03-11  1.695213
 11 2026-03-12  1.626896
 12 2026-03-13  1.395382
 13 2026-03-14  0.736995}

In [ ]:
# Create a copy to work with
data = forecast_by_borough.copy()

for borough in data:
    df = data[borough]
    for i in range(len(df)):
        df.loc[i, 'yhat1'] = round(df.loc[i, 'yhat1'])


wide_df = pd.DataFrame({'ds': data['BRONX']['ds']})
for borough in data:
    wide_df[borough] = data[borough]['yhat1']

wide_df

           ds  BRONX  BROOKLYN  MANHATTAN  QUEENS  STATEN ISLAND
0  2026-03-01    3.0       6.0        4.0     3.0            1.0
1  2026-03-02    7.0      15.0       11.0     7.0            2.0
2  2026-03-03    6.0      15.0       10.0     7.0            2.0
3  2026-03-04    6.0      15.0       10.0     7.0            2.0
4  2026-03-05    6.0      14.0       10.0     7.0            2.0
5  2026-03-06    5.0      12.0        8.0     6.0            1.0
6  2026-03-07    3.0       6.0        4.0     3.0            1.0
7  2026-03-08    3.0       7.0        5.0     3.0            1.0
8  2026-03-09    7.0      16.0       11.0     7.0            2.0
9  2026-03-10    7.0      16.0       11.0     7.0            2.0
10 2026-03-11    6.0      15.0       11.0     7.0            2.0
11 2026-03-12    6.0      15.0       10.0     7.0            2.0
12 2026-03-13    5.0      13.0        9.0     6.0            1.0
13 2026-03-14    3.0       7.0        5.0     3.0            1.0