# Modeling Daily Rat Sightings in New York City

In [82]:
# import packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error


from prophet import Prophet
from pandas.tseries.holiday import USFederalHolidayCalendar
from prophet.diagnostics import cross_validation, performance_metrics
from prophet.plot import plot_cross_validation_metric
from prophet.plot import add_changepoints_to_plot
import itertools

import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning
warnings.simplefilter('ignore', ConvergenceWarning)

## Importing the Data

In [83]:
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)

In [84]:
rs = pd.read_csv('../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
rs['closed_date'] = pd.to_datetime(rs['closed_date'])
rs['resolution_action_updated_date'] = pd.to_datetime(rs['resolution_action_updated_date'])

In [85]:
# Start by cutting off data before 2020-01-01 and after 2026-02-28.
rs = rs[rs['created_date']<'2026-03-01']
rs = rs[rs['created_date']>='2020-01-01']

In [86]:
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')

## Prophet Model

In [87]:
# Create a date range covering 2020 through end of 2025
date_range = pd.date_range(start="2020-01-01", end="2026-02-28")

# Generate US federal holidays
calendar = USFederalHolidayCalendar()
holidays = calendar.holidays(start=date_range.min(), end=date_range.max())

# Build the DataFrame in the same structure as your original
federal_holidays = pd.DataFrame({
    'holiday': 'federal_us',
    'ds': pd.to_datetime(holidays),
    'lower_window': 0,
    'upper_window': 1,
})

holidays = federal_holidays

In [88]:
# Rename columns for Prophet model
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)
results = []

for i, (train_index, test_index) in enumerate(tscv.split(rs)):
    train = rs.iloc[train_index]
    test = rs.iloc[test_index]
    
    model = Prophet(holidays=holidays)
    model.add_country_holidays(country_name='US')

    model.fit(train)
    
    future = model.make_future_dataframe(periods=len(test), freq='D')
    forecast = model.predict(future)
    
    # Obtain predicted values and compare against the actuals.
    y_pred = forecast['yhat'][-len(test):].values
    y_true = test['y'].values
    
    # Calculate RMSE
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    
    # Calculate MAPE
    mape = mean_absolute_percentage_error(y_true, y_pred)
    
    # Append results
    results.append({'fold': i, 'rmse': rmse, 'mape': mape})

# Convert results to a datafrane
prophet_results_df = pd.DataFrame(results)

21:36:51 - cmdstanpy - INFO - Chain [1] start processing
21:36:51 - cmdstanpy - INFO - Chain [1] done processing
21:36:52 - cmdstanpy - INFO - Chain [1] start processing
21:36:52 - cmdstanpy - INFO - Chain [1] done processing
21:36:53 - cmdstanpy - INFO - Chain [1] start processing
21:36:53 - cmdstanpy - INFO - Chain [1] done processing
21:36:54 - cmdstanpy - INFO - Chain [1] start processing
21:36:54 - cmdstanpy - INFO - Chain [1] done processing
21:36:55 - cmdstanpy - INFO - Chain [1] start processing
21:36:56 - cmdstanpy - INFO - Chain [1] done processing
21:36:57 - cmdstanpy - INFO - Chain [1] start processing
21:36:57 - cmdstanpy - INFO - Chain [1] done processing
21:36:58 - cmdstanpy - INFO - Chain [1] start processing
21:36:58 - cmdstanpy - INFO - Chain [1] done processing
21:36:59 - cmdstanpy - INFO - Chain [1] start processing
21:37:00 - cmdstanpy - INFO - Chain [1] done processing
21:37:00 - cmdstanpy - INFO - Chain [1] start processing
21:37:01 - cmdstanpy - INFO - Chain [1] done processing
21:37:02 - cmdstanpy - INFO - Chain [1] start processing
21:37:02 - cmdstanpy - INFO - Chain [1] done processing
21:37:03 - cmdstanpy - INFO - Chain [1] start processing
21:37:03 - cmdstanpy - INFO - Chain [1] done processing
21:37:04 - cmdstanpy - INFO - Chain [1] start processing
21:37:04 - cmdstanpy - INFO - Chain [1] done processing
21:37:05 - cmdstanpy - INFO - Chain [1] start processing
21:37:06 - cmdstanpy - INFO - Chain [1] done processing
21:37:07 - cmdstanpy - INFO - Chain [1] start processing
21:37:07 - cmdstanpy - INFO - Chain [1] done processing
21:37:08 - cmdstanpy - INFO - Chain [1] start processing
21:37:09 - cmdstanpy - INFO - Chain [1] done processing
21:37:09 - cmdstanpy - INFO - Chain [1] start processing
21:37:10 - cmdstanpy - INFO - Chain [1] done processing
21:37:10 - cmdstanpy - INFO - Chain [1] start processing
21:37:11 - cmdstanpy - INFO - Chain [1] done processing
21:37:12 - cmdstanpy - INFO - Chain [1] start processing
21:37:12 - cmdstanpy - INFO - Chain [1] done processing
21:37:13 - cmdstanpy - INFO - Chain [1] start processing
21:37:13 - cmdstanpy - INFO - Chain [1] done processing
21:37:14 - cmdstanpy - INFO - Chain [1] start processing
21:37:14 - cmdstanpy - INFO - Chain [1] done processing
21:37:15 - cmdstanpy - INFO - Chain [1] start processing
21:37:15 - cmdstanpy - INFO - Chain [1] done processing
21:37:16 - cmdstanpy - INFO - Chain [1] start processing
21:37:17 - cmdstanpy - INFO - Chain [1] done processing
21:37:18 - cmdstanpy - INFO - Chain [1] start processing
21:37:18 - cmdstanpy - INFO - Chain [1] done processing
21:37:19 - cmdstanpy - INFO - Chain [1] start processing
21:37:19 - cmdstanpy - INFO - Chain [1] done processing
21:37:20 - cmdstanpy - INFO - Chain [1] start processing
21:37:20 - cmdstanpy - INFO - Chain [1] done processing
21:37:21 - cmdstanpy - INFO - Chain [1] start processing
21:37:21 - cmdstanpy - INFO - Chain [1] done processing

In [94]:
prophet_results_df.loc['mean'] = ['mean',  prophet_results_df['rmse'].mean(), prophet_results_df['mape'].mean()]

In [95]:
prophet_results_df

      fold       rmse      mape
0        0  12.931175  0.246172
1        1   9.286185  0.142636
2        2   7.983666  0.130110
3        3   9.817654  0.143238
4        4  10.903003  0.138791
5        5  15.534582  0.217436
6        6  11.539387  0.145670
7        7  11.299325  0.135217
8        8  10.559222  0.118595
9        9   9.146496  0.113947
10      10  15.403790  0.226627
11      11   9.164685  0.116819
12      12  11.141143  0.119338
13      13  12.065524  0.120530
14      14  18.946567  0.387667
15      15   8.367090  0.157208
16      16  11.798670  0.256426
17      17  15.583406  0.553277
18      18  11.766219  0.308413
19      19  11.907598  0.365745
20      20  10.669815  0.409370
21      21   9.164783  0.405596
22      22   9.808565  0.241197
23      23  11.468369  0.503022
24      24   9.018752  0.362913
25      25  14.222347  0.495702
mean  mean  11.519154  0.252372

## SARIMA Model with auto_arima parameters.

In [72]:
pip install pmdarima

Requirement already satisfied: pmdarima in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (2.1.1)
Requirement already satisfied: joblib>=0.11 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (1.5.3)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (3.2.4)
Requirement already satisfied: numpy>=1.21.6 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (1.26.4)
Requirement already satisfied: pandas>=0.19 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (2.3.3)
Requirement already satisfied: scikit-learn>=0.22 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (1.8.0)
Requirement already satisfied: scipy>=1.13.0 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (1.15.3)
Requirement already satisfied: statsmodels>=0.14.5 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (0.14.6)
Requirement already satisfied: urllib3 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (2.6.3)
Requirement already satisfied: setuptools!=50.0.0,>=42 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (80.10.2)
Requirement already satisfied: packaging>=17.1 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pandas>=0.19->pmdarima) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pandas>=0.19->pmdarima) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pandas>=0.19->pmdarima) (2025.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=0.19->pmdarima) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from scikit-learn>=0.22->pmdarima) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from statsmodels>=0.14.5->pmdarima) (1.0.2)
Note: you may need to restart the kernel to use updated packages.

In [73]:
from pmdarima import auto_arima

In [74]:
def fourier_terms(df, period, n_terms):
    t = np.arange(1, len(df) + 1)
    fourier_df = pd.DataFrame()
    
    for i in range(1, n_terms + 1):
        fourier_df[f'sin_{i}'] = np.sin(2 * np.pi * i * t / period)
        fourier_df[f'cos_{i}'] = np.cos(2 * np.pi * i * t / period)
    
    return fourier_df

In [75]:
# Number of Fourier terms and period (365 for yearly seasonality)
n_terms = 5  # Number of terms for Fourier Terms
period = 365

In [60]:
# Generate Fourier terms and putting it into a list
fourier_train = fourier_terms(rs, period, n_terms)

# Name it exog since it will serve as exogenous features for SARIMAX. This is the X.
exog = fourier_train

In [ ]:
from statsmodels.tsa.statespace.sarimax import SARIMAX

# Make sure the columns for SARIMA model are renamed.
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

results = []

# Loop through each fold
for i, (train_index, test_index) in enumerate(tscv.split(rs)):
    train = rs.iloc[train_index]
    test = rs.iloc[test_index]

    exog_train = exog.iloc[train_index]
    exog_test = exog.iloc[test_index]

    orders = (1,1,1)
    seasonal_orders = (0,0,0,7)
    # # We use auto_arima to get optimal (p, d, q) and (P, D, Q, s) parameters for SARIMAX
    # model_auto = auto_arima(train['y'], 
    #                         exog=exog_train,  # Exogenous Fourier terms for training data
    #                         seasonal=True, 
    #                         m=365,  # Yearly seasonality for daily data
    #                         trace=True, 
    #                         stepwise=True,  # Stepwise search to speed up
    #                         suppress_warnings=True, 
    #                         n_jobs=-1,  # Use all available cores for parallel processing
    #                         maxiter=200,  # Limit the number of iterations
    #                         max_p=3, 
    #                         max_q=3, 
    #                         max_P=2, 
    #                         max_Q=2, 
    #                         d=1, 
    #                         D=1)
    # orders = model_auto.order  # (p, d, q)
    # seasonal_orders = model_auto.seasonal_order  # (P, D, Q, s)
    
    # Fit the SARIMAX model with the exogenous features (Fourier terms)
    model_sarimax = SARIMAX(train['y'], 
                            order=orders,  
                            seasonal_order=seasonal_orders,  
                            exog=exog_train,  # Exogenous Fourier terms for training data
                            enforce_stationarity=False,
                            enforce_invertibility=False)
    
    model_fit = model_sarimax.fit(disp=False)
    
    # Predict for the test period. Have to remember to subtract 1 to get the correct index.
    y_pred = model_fit.predict(start=len(train), end=len(train)+len(test)-1, exog=exog_test, dynamic=False)
    y_true = test['y'].values
    
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)
    results.append({'fold': i, 'rmse': rmse, 'mape': mape})

sarima_results_df = pd.DataFrame(results)

In [96]:
sarima_results_df.loc['mean'] = ['mean',  sarima_results_df['rmse'].mean(), sarima_results_df['mape'].mean()]

In [97]:
sarima_results_df

      fold       rmse      mape
0        0  15.719609  0.240440
1        1  14.271212  0.199697
2        2  12.654641  0.201484
3        3  17.120726  0.263835
4        4  14.470259  0.202554
5        5  17.907910  0.264081
6        6  14.692676  0.176597
7        7  20.815400  0.250376
8        8  20.015043  0.267852
9        9  13.988056  0.166753
10      10  17.332377  0.259642
11      11  14.142204  0.191667
12      12  16.634764  0.184555
13      13  19.536495  0.211381
14      14  20.134967  0.431906
15      15  14.513849  0.297773
16      16  10.708175  0.249026
17      17  15.595443  0.639386
18      18  10.274787  0.201983
19      19  14.260241  0.383895
20      20   7.116006  0.315849
21      21   9.270426  0.522615
22      22  13.158872  0.290013
23      23  12.523939  0.781379
24      24   7.722993  0.289614
25      25  10.310420  0.351192
mean  mean  14.418903  0.301367

## Holt-Winters Model

In [100]:
from statsmodels.tsa.holtwinters import ExponentialSmoothing

In [101]:
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)
results = []
for i, (train_index, test_index) in enumerate(tscv.split(rs)):
    train = rs.iloc[train_index]
    test = rs.iloc[test_index]
    
    # First we fit the Holt-Winters Exponential Smoothing Model to the training data
    holt_winters = ExponentialSmoothing(train['y'], seasonal='add', seasonal_periods=365).fit(optimized=True)
    
    y_pred = holt_winters.forecast(len(test))
    y_true = test['y'].values
    
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)
    results.append({'fold': i, 'rmse': rmse, 'mape': mape})

hw_results_df = pd.DataFrame(results)

In [102]:
hw_results_df.loc['mean'] = ['mean',  hw_results_df['rmse'].mean(), hw_results_df['mape'].mean()]

In [103]:
hw_results_df

      fold       rmse      mape
0        0  17.029947  0.279665
1        1  17.558940  0.255894
2        2  17.312295  0.297496
3        3  22.556060  0.358384
4        4  19.966872  0.268691
5        5  20.725658  0.310186
6        6  22.555124  0.270105
7        7  25.834040  0.311909
8        8  23.343693  0.306820
9        9  21.316698  0.274190
10      10  23.475082  0.358957
11      11  20.733607  0.281012
12      12  18.607673  0.213410
13      13  26.490924  0.314054
14      14  26.457852  0.575931
15      15  17.653667  0.338866
16      16  15.214237  0.350417
17      17  16.538625  0.650859
18      18  13.508845  0.299738
19      19  17.519674  0.500986
20      20  11.076713  0.512212
21      21  12.828411  0.573143
22      22  13.621282  0.367359
23      23  15.432451  0.944308
24      24   6.899231  0.232476
25      25  14.060919  0.400979
mean  mean  18.396866  0.378771

## XGBoost Model

The XGBoost model requires a bit more preparatory work. Our current dataframe rs is quite bare. We will need to add features for use.

In [104]:
rs

              ds   y
0     2020-01-01  17
1     2020-01-02  40
2     2020-01-03  41
3     2020-01-04  25
4     2020-01-05  17
...          ...  ..
2246  2026-02-24  26
2247  2026-02-25  30
2248  2026-02-26  40
2249  2026-02-27  38
2250  2026-02-28  23

[2251 rows x 2 columns]