# Clean Pre2020 Rat Sightings Data

In [32]:
import pandas as pd

In [33]:
# List of files and directory
files = [
    "../data/rat_sightings_data/Rat_Sightings_NYC_2010_2012.csv",
    "../data/rat_sightings_data/Rat_Sightings_NYC_2013_2015.csv",
    "../data/rat_sightings_data/Rat_Sightings_NYC_2016_2017.csv",
    "../data/rat_sightings_data/Rat_Sightings_NYC_2018_2019.csv"
]

# Read and concatenate all CSV files
rs = pd.concat([pd.read_csv(file, low_memory=False) for file in files], ignore_index=True)

In [34]:
rs

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,...,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,24699831,2012-12-31T00:00:00.000,2013-01-30T00:00:00.000,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,NaN,3+ Family Apt. Building,10128.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.776447,-73.946282,POINT (-73.946281604993 40.776447145927)
1,24698865,2012-12-31T00:00:00.000,2013-01-03T00:00:00.000,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,NaN,1-2 Family Dwelling,11413.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.672816,-73.739258,POINT (-73.739258472342 40.672815869624)
2,24699339,2012-12-31T00:00:00.000,2013-01-14T00:00:00.000,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,NaN,3+ Family Apt. Building,10455.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.814492,-73.898123,POINT (-73.898123069878 40.814492281135)
3,24699844,2012-12-31T00:00:00.000,2013-01-03T00:00:00.000,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,NaN,1-2 Family Dwelling,11412.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.697403,-73.761709,POINT (-73.761709065793 40.697402907321)
4,24697961,2012-12-31T00:00:00.000,2013-01-09T00:00:00.000,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,NaN,1-2 Family Dwelling,10305.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.591044,-74.084808,POINT (-74.084807782029 40.591043810415)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140811,38079035,2018-01-01T00:00:00.000,2018-01-16T11:24:54.000,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,NaN,3+ Family Mixed Use Building,11225.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.662337,-73.953730,POINT (-73.953730112836 40.662337010769)
140812,38071595,2018-01-01T00:00:00.000,2018-01-18T00:00:00.000,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,NaN,3+ Family Apt. Building,11216.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.691126,-73.945449,POINT (-73.945448851572 40.691126069319)
140813,38081444,2018-01-01T00:00:00.000,2018-01-17T17:59:46.000,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,NaN,3+ Family Apt. Building,10456.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.837410,-73.910335,POINT (-73.910335492857 40.837409831529)
140814,38076594,2018-01-01T00:00:00.000,2018-02-08T00:00:00.000,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,NaN,3+ Family Apt. Building,11368.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.735647,-73.861824,POINT (-73.861824192522 40.735647496906)
140815,38080127,2018-01-01T00:00:00.000,2018-01-25T00:00:00.000,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,NaN,1-2 Family Dwelling,11691.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.606651,-73.758561,POINT (-73.758561215706 40.606650765219)

In [35]:
# make letters lowercase, replace spaces with underscores, get rid of text after '(' etc

rs.columns = [t.partition('(')[0].strip().lower().replace(' ', '_') for t in rs.columns] #apply to column headers
rs['location_type'] = rs['location_type'].str.strip().str.replace(' ', '_').str.lower()  #apply to location_type column

In [36]:
# make the datetime the correct format
rs['created_date'] = pd.to_datetime(rs['created_date'])

In [37]:
rs = rs[['created_date','incident_zip', 'longitude', 'latitude', 'descriptor', 'location_type',
         'unique_key', 'borough']]

rs['date'] = pd.to_datetime(rs['created_date'])
rs = rs.drop(columns=['created_date'])
rs = rs.sort_values(by='date')

rs

/var/folders/ry/m6r2ndwd10bdv8tvww5hr2680000gn/T/ipykernel_14613/388903800.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rs['date'] = pd.to_datetime(rs['created_date'])

,incident_zip,longitude,latitude,descriptor,location_type,unique_key,borough,date
31630,11206.0,-73.943771,40.692989,Rat Sighting,3+_family_apt._building,15633803,BROOKLYN,2010-01-01 08:29:58
31629,11365.0,-73.809299,40.739983,Rat Sighting,1-2_family_dwelling,15633054,QUEENS,2010-01-01 11:20:45
31628,10027.0,-73.954388,40.807367,Rat Sighting,3+_family_apt._building,15633896,MANHATTAN,2010-01-01 12:11:51
31627,10458.0,-73.890006,40.855513,Rat Sighting,3+_family_apt._building,15633897,BRONX,2010-01-01 12:12:04
31626,11218.0,-73.967757,40.635654,Rat Sighting,vacant_building,15633828,BROOKLYN,2010-01-01 14:15:27
...,...,...,...,...,...,...,...,...
106659,10460.0,-73.896202,40.834659,Rat Sighting,3+_family_apt._building,45280215,BRONX,2019-12-31 20:23:25
106658,10460.0,-73.896202,40.834659,Rat Sighting,3+_family_apt._building,45279550,BRONX,2019-12-31 20:25:45
106657,10003.0,-73.987701,40.727059,Rat Sighting,residential_building,45282718,MANHATTAN,2019-12-31 21:41:56
106656,10033.0,-73.936596,40.846331,Rat Sighting,3+_family_apt._building,45280182,MANHATTAN,2019-12-31 22:00:23
106655,11205.0,-73.964357,40.693601,Rat Sighting,commercial_building,45279319,BROOKLYN,2019-12-31 23:02:55

In [38]:
rs

,incident_zip,longitude,latitude,descriptor,location_type,unique_key,borough,date
31630,11206.0,-73.943771,40.692989,Rat Sighting,3+_family_apt._building,15633803,BROOKLYN,2010-01-01 08:29:58
31629,11365.0,-73.809299,40.739983,Rat Sighting,1-2_family_dwelling,15633054,QUEENS,2010-01-01 11:20:45
31628,10027.0,-73.954388,40.807367,Rat Sighting,3+_family_apt._building,15633896,MANHATTAN,2010-01-01 12:11:51
31627,10458.0,-73.890006,40.855513,Rat Sighting,3+_family_apt._building,15633897,BRONX,2010-01-01 12:12:04
31626,11218.0,-73.967757,40.635654,Rat Sighting,vacant_building,15633828,BROOKLYN,2010-01-01 14:15:27
...,...,...,...,...,...,...,...,...
106659,10460.0,-73.896202,40.834659,Rat Sighting,3+_family_apt._building,45280215,BRONX,2019-12-31 20:23:25
106658,10460.0,-73.896202,40.834659,Rat Sighting,3+_family_apt._building,45279550,BRONX,2019-12-31 20:25:45
106657,10003.0,-73.987701,40.727059,Rat Sighting,residential_building,45282718,MANHATTAN,2019-12-31 21:41:56
106656,10033.0,-73.936596,40.846331,Rat Sighting,3+_family_apt._building,45280182,MANHATTAN,2019-12-31 22:00:23
106655,11205.0,-73.964357,40.693601,Rat Sighting,commercial_building,45279319,BROOKLYN,2019-12-31 23:02:55

In [39]:
rs.to_csv("../data/cleaned_rat_sightings_data/cleaned_rat_sightings_pre2020.csv", index=False)